---
- hosts: CI-BUILDS
  #remote_user: perezjc
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  #sudo: yes
  #gather_facts: no
  tasks:
  - name: Set up authorized_keys for the ansible user
    authorized_key: user=ansible key="{{ item }}"
    with_file:
      - /home/PerezJu/.ssh/id_rsa.pub

