---
- hosts: CI-BUILDS
  #remote_user: perezjc
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  #sudo: yes
  #gather_facts: no
  tasks:
  - name: "Add ansible user"
    user: name=ansible 
          createhome=yes 
          comment="ansible" 
          group=wheel
          password="$6$rounds=656000$P757oDUFkQTBt/9.$D7BFzr/1HhDx3rTzc96WJdRFLwnmTRSvHS0A3sjCRNidLeNVKRr8oEGmjajh8i5B3iCdD5Ow3h7/D0ErH.R2B0"
    register: newuser